Config = {
    ScreenPosition = 2, -- 0 = top-left, 1 = top-right, 2 = bottom-left, 3 = bottom-right
    Shape = 'square',   -- "circle","square"

    KnownGameCoords = {
        { -116507, -81989 },
        { 124069,  -178853 },
        { -25227,  217105 }
    },

    KnownImageCoords = {
        { 3171.5, 2431.8 },
        { 4590.8, 3003 },
        { 3711,   663 }
    },

    MaxMinimapBlipsCount = 30,

    MapBlips = {
        { name = 'Sushi',             coords = { x = 11865, y = -111372, z = 110 },     imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Sushi',             coords = { x = 4139, y = -265021, z = -59 },      imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Sushi',             coords = { x = -133448, y = 71842, z = -53 },     imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Sushi',             coords = { x = 98982, y = 124579, z = 100 },      imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Sushi',             coords = { x = 143648, y = -58366, z = 101 },     imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Steakhouse',        coords = { x = -49793, y = -25409, z = 58 },      imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Steakhouse',        coords = { x = -124701, y = 76829, z = 58 },      imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Diner',             coords = { x = -136952, y = 101131, z = 80 },     imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'FastFood',          coords = { x = -30773, y = -224791, z = 205 },    imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'FastFood',          coords = { x = -34032, y = -73824, z = 211 },     imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'FastFood',          coords = { x = 149626, y = -58093, z = 211 },     imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'FastFood',          coords = { x = -139078, y = 126519, z = 191 },    imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'FastFood',          coords = { x = 119952, y = 28478, z = 211 },      imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Donut Shop',        coords = { x = -6425, y = -73078, z = -12 },      imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Coffee Shop',       coords = { x = 10310, y = -23670, z = 73 },       imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Coffee Shop',       coords = { x = 115833, y = 75664, z = 67 },       imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Pizza Shop',        coords = { x = 156857, y = -78392, z = 15 },      imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Pizza Shop',        coords = { x = -253219, y = 29525, z = 15 },      imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Pizza Shop',        coords = { x = 17115, y = -42230, z = 11 },       imgUrl = './media/map-icons/Food-icon.svg',        group = 'food' },
        { name = 'Convenience Store', coords = { x = 121242, y = -53703, z = -38 },     imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Convenience Store', coords = { x = 115768, y = 190999, z = -38 },     imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Convenience Store', coords = { x = 14747, y = 95787, z = -25 },       imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Convenience Store', coords = { x = -223524, y = 153585, z = -36 },    imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Convenience Store', coords = { x = -140829, y = 184028, z = -8 },     imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Convenience Store', coords = { x = 4980, y = 95399, z = 7 },          imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Convenience Store', coords = { x = -54567, y = -41338, z = 284 },     imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Convenience Store', coords = { x = 16988, y = -46371, z = 2.0 },      imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Jewelry',           coords = { x = -27356, y = 138919, z = 105 },     imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Jewelry',           coords = { x = -129314, y = 207884, z = 84 },     imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Car Wash',          coords = { x = 119068, y = 20456, z = 705 },      imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Car Wash',          coords = { x = 67121, y = 194761, z = 701 },      imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Car Wash',          coords = { x = -59123, y = 168340, z = 708 },     imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Car Wash',          coords = { x = -160450, y = 173508, z = 694 },    imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Car Wash',          coords = { x = -69662, y = -200696, z = 706 },    imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Furniture',         coords = { x = 103543, y = 123954, z = 76 },      imgUrl = './media/map-icons/shop-icon.svg',        group = 'shop' },
        { name = 'Car Dealership',    coords = { x = -190503, y = 212136, z = 96 },     imgUrl = './media/map-icons/Cars-icon.svg',        group = 'dealership' },
        { name = 'Car Dealership',    coords = { x = -34630, y = -233743, z = 99 },     imgUrl = './media/map-icons/Cars-icon.svg',        group = 'dealership' },
        { name = 'Hotel',             coords = { x = 73237, y = 149518, z = -215 },     imgUrl = './media/map-icons/Hotel-icon.svg',       group = 'hotel' },
        { name = 'Motel',             coords = { x = -117407, y = -75376, z = 100 },    imgUrl = './media/map-icons/Hotel-icon.svg',       group = 'hotel' },
        { name = 'Gas Station',       coords = { x = 9700, y = 155658, z = 113 },       imgUrl = './media/map-icons/Gas-station-icon.svg', group = 'gas_station' },
        { name = 'Gas Station',       coords = { x = -126157, y = -81333, z = 88 },     imgUrl = './media/map-icons/Gas-station-icon.svg', group = 'gas_station' },
        { name = 'Gas Station',       coords = { x = 109571, y = 135976, z = 99 },      imgUrl = './media/map-icons/Gas-station-icon.svg', group = 'gas_station' },
        { name = 'Gas Station',       coords = { x = 157384, y = -82454, z = 100 },     imgUrl = './media/map-icons/Gas-station-icon.svg', group = 'gas_station' },
        { name = 'Gas Station',       coords = { x = -13235, y = -212481, z = 109 },    imgUrl = './media/map-icons/Gas-station-icon.svg', group = 'gas_station' },
        { name = 'Gas Station',       coords = { x = -134276, y = -8475, z = 88 },      imgUrl = './media/map-icons/Gas-station-icon.svg', group = 'gas_station' },
        { name = 'Mechanic',          coords = { x = 37783, y = 234082, z = -40 },      imgUrl = './media/map-icons/Service-icon.svg',     group = 'mechanic' },
        { name = 'Mechanic',          coords = { x = -66917, y = -203901, z = -39 },    imgUrl = './media/map-icons/Service-icon.svg',     group = 'mechanic' },
        { name = 'Nightclub',         coords = { x = -54776, y = -34335, z = 427 },     imgUrl = './media/map-icons/Bar-icon.svg',         group = 'bar' },
        { name = 'Nightclub',         coords = { x = 103582, y = 165740, z = 100 },     imgUrl = './media/map-icons/Bar-icon.svg',         group = 'bar' },
        { name = 'Nightclub',         coords = { x = 103582, y = 165740, z = 100 },     imgUrl = './media/map-icons/Bar-icon.svg',         group = 'bar' },
        { name = 'Bar',               coords = { x = -142783, y = 121461, z = 87 },     imgUrl = './media/map-icons/Bar-icon.svg',         group = 'bar' },
        { name = 'Bar',               coords = { x = 3306, y = -261000, z = 87 },       imgUrl = './media/map-icons/Bar-icon.svg',         group = 'bar' },
        { name = 'Bar',               coords = { x = -42879, y = -114061, z = 197 },    imgUrl = './media/map-icons/Bar-icon.svg',         group = 'bar' },
        { name = 'Bar',               coords = { x = 136533, y = 205267, z = -97 },     imgUrl = './media/map-icons/Bar-icon.svg',         group = 'bar' },
        { name = 'High Tier Office',  coords = { x = -13561, y = -105333, z = 15327 },  imgUrl = './media/map-icons/Marker.svg',           group = 'high_office' },
        { name = 'High Tier Office',  coords = { x = -13561, y = -105333, z = 16482 },  imgUrl = './media/map-icons/Marker.svg',           group = 'high_office' },
        { name = 'High Tier Office',  coords = { x = -36203, y = 177519, z = 95 },      imgUrl = './media/map-icons/Marker.svg',           group = 'high_office' },
        { name = 'High Tier Office',  coords = { x = -24335, y = 164707, z = 100 },     imgUrl = './media/map-icons/Marker.svg',           group = 'high_office' },
        { name = 'High Tier Office',  coords = { x = -4138, y = 168821, z = 110 },      imgUrl = './media/map-icons/Marker.svg',           group = 'high_office' },
        { name = 'High Tier Office',  coords = { x = 79020, y = 216805, z = 99 },       imgUrl = './media/map-icons/Marker.svg',           group = 'high_office' },
        { name = 'High Tier Office',  coords = { x = 62304, y = 162411, z = -164 },     imgUrl = './media/map-icons/Marker.svg',           group = 'high_office' },
        { name = 'Med Tier Office',   coords = { x = 21826, y = -107151, z = 105 },     imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -11180, y = 72880, z = 100 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -59410, y = 30900, z = 110 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -57150, y = 30900, z = 110 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -12055, y = 55690, z = 100 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -123957, y = -14769, z = 77 },     imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -33034, y = 61763, z = 100 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = 89080, y = 214103, z = 100 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = 112116, y = 200192, z = 99 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = 77910, y = 139445, z = 100 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -125023, y = 190561, z = 100 },    imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -23843, y = 177131, z = 100 },     imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -48229, y = 142812, z = 109 },     imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -8808, y = 42106, z = 76 },        imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -54378, y = 110205, z = 108 },     imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -48440, y = 111654, z = 105 },     imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -9791, y = 175716, z = 109 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = 76340, y = 99418, z = 112. },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -139261, y = 176554, z = 98 },     imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = 5398, y = 106890, z = 93 },        imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -4472, y = 153102, z = 110 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Med Tier Office',   coords = { x = -250977, y = 3052, z = -174 },     imgUrl = './media/map-icons/Marker.svg',           group = 'med_office' },
        { name = 'Low Tier Office',   coords = { x = 12373, y = -259547, z = 92 },      imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = 112102, y = 142321, z = 95 },      imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = -252699, y = -3433, z = 79 },      imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = -115081, y = -14438, z = 79 },     imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = 43347, y = 206844, z = 95 },       imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = 688, y = 164279, z = 100 },        imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = -2269, y = 162007, z = 100 },      imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = -2566, y = 159385, z = 100 },      imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = 2977, y = 158709, z = 100 },       imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = -26953, y = 142171, z = 90 },      imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = -26953, y = 142171, z = 90 },      imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = -30541, y = 166851, z = 100 },     imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = -55181, y = -81942, z = 110 },     imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = 25989, y = -73658, z = 103 },      imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = -51001, y = -3853, z = 105 },      imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = 80879, y = 248263, z = 93 },       imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = 135359, y = 31019, z = 93 },       imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = -44327, y = -231286, z = 99 },     imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = -136701, y = 195821, z = 86 },     imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'Low Tier Office',   coords = { x = -136225, y = 197511, z = 86 },     imgUrl = './media/map-icons/Marker.svg',           group = 'low_office' },
        { name = 'High Tier Hideout', coords = { x = -50307, y = 183980, z = 93 },      imgUrl = './media/map-icons/Marker.svg',           group = 'high_hideout' },
        { name = 'High Tier Hideout', coords = { x = -179363, y = 202239, z = 88 },     imgUrl = './media/map-icons/Marker.svg',           group = 'high_hideout' },
        { name = 'High Tier Hideout', coords = { x = 135394, y = 60922, z = 97 },       imgUrl = './media/map-icons/Marker.svg',           group = 'high_hideout' },
        { name = 'High Tier Hideout', coords = { x = 48503, y = -218857, z = 100 },     imgUrl = './media/map-icons/Marker.svg',           group = 'high_hideout' },
        { name = 'High Tier Hideout', coords = { x = -52797, y = -226521, z = 101 },    imgUrl = './media/map-icons/Marker.svg',           group = 'high_hideout' },
        { name = 'High Tier Hideout', coords = { x = -193910, y = -123721, z = -1019 }, imgUrl = './media/map-icons/Marker.svg',           group = 'high_hideout' },
        { name = 'High Tier Hideout', coords = { x = -35470, y = -109849, z = 260 },    imgUrl = './media/map-icons/Marker.svg',           group = 'high_hideout' },
        { name = 'Med Tier Hideout',  coords = { x = 24049, y = 121097, z = 97 },       imgUrl = './media/map-icons/Marker.svg',           group = 'med_hideout' },
        { name = 'Med Tier Hideout',  coords = { x = 82697, y = 254126, z = 70 },       imgUrl = './media/map-icons/Marker.svg',           group = 'med_hideout' },
        { name = 'Med Tier Hideout',  coords = { x = 83018, y = -108582, z = 97 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_hideout' },
        { name = 'Med Tier Hideout',  coords = { x = 148818, y = -77090, z = 97 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_hideout' },
        { name = 'Med Tier Hideout',  coords = { x = -10544, y = -235659, z = 105 },    imgUrl = './media/map-icons/Marker.svg',           group = 'med_hideout' },
        { name = 'Med Tier Hideout',  coords = { x = -136026, y = 32730, z = 88 },      imgUrl = './media/map-icons/Marker.svg',           group = 'med_hideout' },
        { name = 'Low Tier Hideout',  coords = { x = -35694, y = -84651, z = 104 },     imgUrl = './media/map-icons/Marker.svg',           group = 'low_hideout' },
        { name = 'Low Tier Hideout',  coords = { x = 138204, y = -154330, z = 97 },     imgUrl = './media/map-icons/Marker.svg',           group = 'low_hideout' },
        { name = 'Low Tier Hideout',  coords = { x = -8688, y = -219698, z = 105 },     imgUrl = './media/map-icons/Marker.svg',           group = 'low_hideout' },
        { name = 'Low Tier Hideout',  coords = { x = -192951, y = 151617, z = 88 },     imgUrl = './media/map-icons/Marker.svg',           group = 'low_hideout' },
        { name = 'Low Tier Hideout',  coords = { x = -269395, y = 56976, z = 88 },      imgUrl = './media/map-icons/Marker.svg',           group = 'low_hideout' },
        { name = 'Low Tier Hideout',  coords = { x = -128367, y = -71926, z = 88 },     imgUrl = './media/map-icons/Marker.svg',           group = 'low_hideout' },
        { name = 'Mall',              coords = { x = 138863, y = 171462, z = -144 },    imgUrl = './media/map-icons/Marker.svg',           group = 'mall' },
        { name = 'Construction',      coords = { x = -131680, y = -131754, z = -1013 }, imgUrl = './media/map-icons/Marker.svg',           group = 'construction' },
        { name = 'Construction',      coords = { x = -193910, y = -123721, z = -1019 }, imgUrl = './media/map-icons/Marker.svg',           group = 'construction' },
        { name = 'Construction',      coords = { x = 171841, y = 69228, z = -1019 },    imgUrl = './media/map-icons/Marker.svg',           group = 'construction' },
        { name = 'Chemical Plant',    coords = { x = -170522, y = -92537, z = -364 },   imgUrl = './media/map-icons/Marker.svg',           group = 'chemical' },
        { name = 'Prison',            coords = { x = -126825, y = -179114, z = -504 },  imgUrl = './media/map-icons/Police-icon.svg',      group = 'police' },
        { name = 'Military Base',     coords = { x = 192867, y = 134267, z = -194 },    imgUrl = './media/map-icons/Police-icon.svg',      group = 'police' },
        { name = 'Fire Dept',         coords = { x = -35157, y = -219646, z = 943 },    imgUrl = './media/map-icons/Medicine-icon.svg',    group = 'fire_dept' },
        { name = 'Fire Dept',         coords = { x = 108611, y = 130370, z = 939 },     imgUrl = './media/map-icons/Medicine-icon.svg',    group = 'fire_dept' },
        { name = 'Fire Dept',         coords = { x = -254012, y = 81794, z = 929 },     imgUrl = './media/map-icons/Medicine-icon.svg',    group = 'fire_dept' },
        { name = 'Fire Dept',         coords = { x = 18616, y = -82894, z = 941 },      imgUrl = './media/map-icons/Medicine-icon.svg',    group = 'fire_dept' },
        { name = 'Bank',              coords = { x = -64918, y = -93403, z = -515 },    imgUrl = './media/map-icons/Bank-icon.svg',        group = 'bank' },
        { name = 'Bank',              coords = { x = -56171, y = -1784, z = -505 },     imgUrl = './media/map-icons/Bank-icon.svg',        group = 'bank' },
        { name = 'Bank',              coords = { x = 21715, y = 73269, z = -496 },      imgUrl = './media/map-icons/Bank-icon.svg',        group = 'bank' },
        { name = 'Bank',              coords = { x = 74556, y = 162713, z = -512 },     imgUrl = './media/map-icons/Bank-icon.svg',        group = 'bank' },
        { name = 'Bank',              coords = { x = -114420, y = 201148, z = 62 },     imgUrl = './media/map-icons/Bank-icon.svg',        group = 'bank' },
        { name = 'Casino',            coords = { x = -28970, y = 98494, z = -305 },     imgUrl = './media/map-icons/Casino-icon.svg',      group = 'casino' },
        { name = 'Casino',            coords = { x = -31791, y = 98736, z = 7667 },     imgUrl = './media/map-icons/Casino-icon.svg',      group = 'casino' },
        { name = 'City Hall',         coords = { x = -44954, y = 38432, z = 108 },      imgUrl = './media/map-icons/Education-icon.svg',   group = 'city_hall' },
        { name = 'Movie Theater',     coords = { x = -40776, y = 49595, z = 77 },       imgUrl = './media/map-icons/Cinema-icon.svg',      group = 'cinema' },
        { name = 'Amazon',            coords = { x = -207310, y = 153823, z = -39 },    imgUrl = './media/map-icons/Business-icon.svg',    group = 'warehouse' },
        { name = 'Amazon',            coords = { x = 1485, y = -210093, z = -65 },      imgUrl = './media/map-icons/Business-icon.svg',    group = 'warehouse' },
        { name = 'Amazon',            coords = { x = 63687, y = -219156, z = -65 },     imgUrl = './media/map-icons/Business-icon.svg',    group = 'warehouse' },
        { name = 'Amazon',            coords = { x = 22490, y = 102707, z = -72 },      imgUrl = './media/map-icons/Business-icon.svg',    group = 'warehouse' },
        { name = 'Amazon',            coords = { x = 146100, y = 91502, z = -65 },      imgUrl = './media/map-icons/Business-icon.svg',    group = 'warehouse' },
        { name = 'Bus Station',       coords = { x = -44822, y = -21591, z = 104 },     imgUrl = './media/map-icons/Station-icon.svg',     group = 'bus_station' },
        { name = 'Port Area',         coords = { x = 169861, y = -164689, z = -1017 },  imgUrl = './media/map-icons/Port-icon.svg',        group = 'misc' },
        { name = 'Gun Store',         coords = { x = -2053, y = -89885, z = 206 },      imgUrl = './media/map-icons/Gun-icon.svg',         group = 'gun_store' },
        { name = 'Gun Store',         coords = { x = 53952, y = -192375, z = 194 },     imgUrl = './media/map-icons/Gun-icon.svg',         group = 'gun_store' },
        { name = 'Gun Store',         coords = { x = 69022, y = 197398, z = 194 },      imgUrl = './media/map-icons/Gun-icon.svg',         group = 'gun_store' },
        { name = 'Gun Store',         coords = { x = -139307, y = 184192, z = 190 },    imgUrl = './media/map-icons/Gun-icon.svg',         group = 'gun_store' },
        { name = 'Retail',            coords = { x = 32765, y = -108548, z = 110 },     imgUrl = './media/map-icons/Clothing-icon.svg',    group = 'clothing' },
        { name = 'Retail',            coords = { x = -38983, y = -42487, z = 403 },     imgUrl = './media/map-icons/Clothing-icon.svg',    group = 'clothing' },
        { name = 'Retail',            coords = { x = 20297, y = 5168, z = 112 },        imgUrl = './media/map-icons/Clothing-icon.svg',    group = 'clothing' },
        { name = 'Retail',            coords = { x = -38844, y = 169224, z = 98 },      imgUrl = './media/map-icons/Clothing-icon.svg',    group = 'clothing' },
        { name = 'Barbershop',        coords = { x = -61812, y = 30224, z = 101 },      imgUrl = './media/map-icons/Clothing-icon.svg',    group = 'barber' },
        { name = 'Barbershop',        coords = { x = 100468, y = 122767, z = 83 },      imgUrl = './media/map-icons/Clothing-icon.svg',    group = 'barber' },
    }
}

return Config
