Config = {
    Keybind = 'F3',
    Emotes = {
        -- Taunts
        YouHere = { name = 'Taunt - You Here', animation_path = 'nanos-world::A_Mannequin_Taunt_YouHere', slot_type = AnimationSlotType.UpperBody, loop = true },
        Bow = { name = 'Taunt - Bow', animation_path = 'nanos-world::A_Mannequin_Taunt_Bow', slot_type = AnimationSlotType.UpperBody, loop = true },
        ButtSlap_01 = { name = 'Taunt - ButtSlap 01', animation_path = 'nanos-world::A_Mannequin_Taunt_ButtSlap_01', slot_type = AnimationSlotType.FullBody, loop = true },
        ButtSlap_02 = { name = 'Taunt - ButtSlap 02', animation_path = 'nanos-world::A_Mannequin_Taunt_ButtSlap_02', slot_type = AnimationSlotType.FullBody, loop = true },
        CallMe = { name = 'Taunt - Call Me', animation_path = 'nanos-world::A_Mannequin_Taunt_CallMe', slot_type = AnimationSlotType.UpperBody, loop = true },
        Chop = { name = 'Taunt - Chop', animation_path = 'nanos-world::A_Mannequin_Taunt_Chop', slot_type = AnimationSlotType.UpperBody, loop = true },
        Clap = { name = 'Taunt - Clap', animation_path = 'nanos-world::A_Mannequin_Taunt_Clap', slot_type = AnimationSlotType.UpperBody, loop = true },
        ComeAtMe = { name = 'Taunt - Come At Me', animation_path = 'nanos-world::A_Mannequin_Taunt_ComeAtMe', slot_type = AnimationSlotType.UpperBody, loop = true },
        CrossArms = { name = 'Taunt - Cross Arms', animation_path = 'nanos-world::A_Mannequin_Taunt_CrossArms', slot_type = AnimationSlotType.UpperBody, loop = true },
        Crutch = { name = 'Taunt - Crutch', animation_path = 'nanos-world::A_Mannequin_Taunt_Crutch', slot_type = AnimationSlotType.UpperBody, loop = true },
        Dab = { name = 'Taunt - Dab', animation_path = 'nanos-world::A_Mannequin_Taunt_Dab', slot_type = AnimationSlotType.UpperBody, loop = true },
        DustOff = { name = 'Taunt - Dust Off', animation_path = 'nanos-world::A_Mannequin_Taunt_DustOff', slot_type = AnimationSlotType.UpperBody, loop = true },
        EarCom = { name = 'Taunt - Ear Communication', animation_path = 'nanos-world::A_Mannequin_Taunt_EarCom', slot_type = AnimationSlotType.UpperBody, loop = true },
        EyesOnYou = { name = 'Taunt - Eyes On You', animation_path = 'nanos-world::A_Mannequin_Taunt_EyesOnYou', slot_type = AnimationSlotType.UpperBody, loop = true },
        FacePalm = { name = 'Taunt - Face Palm', animation_path = 'nanos-world::A_Mannequin_Taunt_FacePalm', slot_type = AnimationSlotType.UpperBody, loop = true },
        FingerGun = { name = 'Taunt - Finger Gun', animation_path = 'nanos-world::A_Mannequin_Taunt_FingerGun', slot_type = AnimationSlotType.UpperBody, loop = true },
        FistCrush = { name = 'Taunt - Fist Crush', animation_path = 'nanos-world::A_Mannequin_Taunt_FistCrush', slot_type = AnimationSlotType.UpperBody, loop = true },
        FistPump_01 = { name = 'Taunt - Fist Pump 01', animation_path = 'nanos-world::A_Mannequin_Taunt_FistPump_01', slot_type = AnimationSlotType.UpperBody, loop = true },
        FistPump_02 = { name = 'Taunt - Fist Pump 02', animation_path = 'nanos-world::A_Mannequin_Taunt_FistPump_02', slot_type = AnimationSlotType.UpperBody, loop = true },
        Flex_01 = { name = 'Taunt - Flex 01', animation_path = 'nanos-world::A_Mannequin_Taunt_Flex_01', slot_type = AnimationSlotType.UpperBody, loop = true },
        Flex_02 = { name = 'Taunt - Flex 02', animation_path = 'nanos-world::A_Mannequin_Taunt_Flex_02', slot_type = AnimationSlotType.UpperBody, loop = true },
        Flex_03 = { name = 'Taunt - Flex 03', animation_path = 'nanos-world::A_Mannequin_Taunt_Flex_03', slot_type = AnimationSlotType.UpperBody, loop = true },
        Halt = { name = 'Taunt - Halt', animation_path = 'nanos-world::A_Mannequin_Taunt_Halt', slot_type = AnimationSlotType.UpperBody, loop = true },
        HandOnHips = { name = 'Taunt - Hand on Hips', animation_path = 'nanos-world::A_Mannequin_Taunt_HandOnHips', slot_type = AnimationSlotType.UpperBody, loop = true },
        HandPunch = { name = 'Taunt - Hand Punch', animation_path = 'nanos-world::A_Mannequin_Taunt_HandPunch', slot_type = AnimationSlotType.UpperBody, loop = true },
        Heart = { name = 'Taunt - Heart', animation_path = 'nanos-world::A_Mannequin_Taunt_Heart', slot_type = AnimationSlotType.UpperBody, loop = true },
        Jog = { name = 'Taunt - Jog', animation_path = 'nanos-world::A_Mannequin_Taunt_Jog', slot_type = AnimationSlotType.FullBody, loop = true },
        Jojo = { name = 'Taunt - Jojo', animation_path = 'nanos-world::A_Mannequin_Taunt_Jojo', slot_type = AnimationSlotType.UpperBody, loop = true },
        Knees = { name = 'Taunt - Knees', animation_path = 'nanos-world::A_Mannequin_Taunt_Knees', slot_type = AnimationSlotType.UpperBody, loop = true },
        Kunfu = { name = 'Taunt - Kungfu', animation_path = 'nanos-world::A_Mannequin_Taunt_Kunfu', slot_type = AnimationSlotType.UpperBody, loop = true },
        NeckSlit = { name = 'Taunt - Neck Slit', animation_path = 'nanos-world::A_Mannequin_Taunt_NeckSlit', slot_type = AnimationSlotType.UpperBody, loop = true },
        OK = { name = 'Taunt - OK', animation_path = 'nanos-world::A_Mannequin_Taunt_OK', slot_type = AnimationSlotType.UpperBody, loop = true },
        Point = { name = 'Taunt - Point', animation_path = 'nanos-world::A_Mannequin_Taunt_Point', slot_type = AnimationSlotType.UpperBody, loop = true },
        Ponder = { name = 'Taunt - Ponder', animation_path = 'nanos-world::A_Mannequin_Taunt_Ponder', slot_type = AnimationSlotType.UpperBody, loop = true },
        Praise = { name = 'Taunt - Praise', animation_path = 'nanos-world::A_Mannequin_Taunt_Praise', slot_type = AnimationSlotType.UpperBody, loop = true },
        Salute_01 = { name = 'Taunt - Salute 01', animation_path = 'nanos-world::A_Mannequin_Taunt_Salute_01', slot_type = AnimationSlotType.UpperBody, loop = true },
        Salute_02 = { name = 'Taunt - Salute 02', animation_path = 'nanos-world::A_Mannequin_Taunt_Salute_02', slot_type = AnimationSlotType.UpperBody, loop = true },
        Savage = { name = 'Taunt - Savage', animation_path = 'nanos-world::A_Mannequin_Taunt_Savage', slot_type = AnimationSlotType.UpperBody, loop = true },
        Shoosh = { name = 'Taunt - Shoosh', animation_path = 'nanos-world::A_Mannequin_Taunt_Shoosh', slot_type = AnimationSlotType.UpperBody, loop = true },
        Shrug = { name = 'Taunt - Shrug', animation_path = 'nanos-world::A_Mannequin_Taunt_Shrug', slot_type = AnimationSlotType.UpperBody, loop = true },
        Streach = { name = 'Taunt - Stretch', animation_path = 'nanos-world::A_Mannequin_Taunt_Streach', slot_type = AnimationSlotType.UpperBody, loop = true },
        Sweat = { name = 'Taunt - Sweat', animation_path = 'nanos-world::A_Mannequin_Taunt_Sweat', slot_type = AnimationSlotType.UpperBody, loop = true },
        TheHeavins = { name = 'Taunt - The Heavins', animation_path = 'nanos-world::A_Mannequin_Taunt_TheHeavins', slot_type = AnimationSlotType.UpperBody, loop = true },
        ThumbsDown = { name = 'Taunt - Thumbs Down', animation_path = 'nanos-world::A_Mannequin_Taunt_ThumbsDown', slot_type = AnimationSlotType.UpperBody, loop = true },
        ThumbsOnEars = { name = 'Taunt - Thumbs on Ears', animation_path = 'nanos-world::A_Mannequin_Taunt_ThumbsOnEars', slot_type = AnimationSlotType.UpperBody, loop = true },
        ThumbsUp_01 = { name = 'Taunt - Thumbs Up 01', animation_path = 'nanos-world::A_Mannequin_Taunt_ThumbsUp_01', slot_type = AnimationSlotType.UpperBody, loop = true },
        ThumbsUp_02 = { name = 'Taunt - Thumbs Up 02', animation_path = 'nanos-world::A_Mannequin_Taunt_ThumbsUp_02', slot_type = AnimationSlotType.UpperBody, loop = true },
        Victory = { name = 'Taunt - Victory', animation_path = 'nanos-world::A_Mannequin_Taunt_Victory', slot_type = AnimationSlotType.UpperBody, loop = true },
        Watch = { name = 'Taunt - Watch', animation_path = 'nanos-world::A_Mannequin_Taunt_Watch', slot_type = AnimationSlotType.UpperBody, loop = true },
        Wave = { name = 'Taunt - Wave', animation_path = 'nanos-world::A_Mannequin_Taunt_Wave', slot_type = AnimationSlotType.UpperBody, loop = true },
        -- Generic
        Body_Stretch_01 = { name = 'Generic - Body Stretch 1', animation_path = 'nanos-world::A_Mannequin_Body_Stretch_01', slot_type = AnimationSlotType.UpperBody, loop = true },
        Body_Stretch_02 = { name = 'Generic - Body Stretch 2', animation_path = 'nanos-world::A_Mannequin_Body_Stretch_02', slot_type = AnimationSlotType.UpperBody, loop = true },
        Body_Stretch_03 = { name = 'Generic - Body Stretch 3', animation_path = 'nanos-world::A_Mannequin_Body_Stretch_03', slot_type = AnimationSlotType.UpperBody, loop = true },
        Body_Stretch_04 = { name = 'Generic - Body Stretch 4', animation_path = 'nanos-world::A_Mannequin_Body_Stretch_04', slot_type = AnimationSlotType.UpperBody, loop = true },
        Bow_01 = { name = 'Generic - Bow 1', animation_path = 'nanos-world::A_Mannequin_Bow_01', slot_type = AnimationSlotType.UpperBody, loop = false },
        Bow_02 = { name = 'Generic - Bow 2', animation_path = 'nanos-world::A_Mannequin_Bow_02', slot_type = AnimationSlotType.UpperBody, loop = false },
        Brush_Of_Dust = { name = 'Generic - Brush of Dust', animation_path = 'nanos-world::A_Mannequin_Brush_Of_Dust', slot_type = AnimationSlotType.UpperBody, loop = false },
        Call_Guards = { name = 'Generic - Call Guards', animation_path = 'nanos-world::A_Mannequin_Call_Guards', slot_type = AnimationSlotType.UpperBody, loop = false },
        Call_Someone_01 = { name = 'Generic - Call Someone 1', animation_path = 'nanos-world::A_Mannequin_Call_Someone_01', slot_type = AnimationSlotType.UpperBody, loop = false },
        Call_Someone_02 = { name = 'Generic - Call Someone 2', animation_path = 'nanos-world::A_Mannequin_Call_Someone_02', slot_type = AnimationSlotType.UpperBody, loop = false },
        Check_Equipment_01 = { name = 'Generic - Check Equipment 1', animation_path = 'nanos-world::A_Mannequin_Check_Equipment_01', slot_type = AnimationSlotType.UpperBody, loop = false },
        Check_Equipment_02 = { name = 'Generic - Check Equipment 2', animation_path = 'nanos-world::A_Mannequin_Check_Equipment_02', slot_type = AnimationSlotType.UpperBody, loop = false },
        Check_Equipment_03 = { name = 'Generic - Check Equipment 3', animation_path = 'nanos-world::A_Mannequin_Check_Equipment_03', slot_type = AnimationSlotType.UpperBody, loop = false },
        Clap_01 = { name = 'Generic - Clap 1', animation_path = 'nanos-world::A_Mannequin_Clap_01', slot_type = AnimationSlotType.UpperBody, loop = false },
        Clap_02 = { name = 'Generic - Clap 2', animation_path = 'nanos-world::A_Mannequin_Clap_02', slot_type = AnimationSlotType.UpperBody, loop = false },
        Crowd_Cheer = { name = 'Generic - Crowd Cheer', animation_path = 'nanos-world::A_Mannequin_Crowd_Cheer', slot_type = AnimationSlotType.UpperBody, loop = false },
        Deep_Breath_Sad = { name = 'Generic - Deep Breath Sad', animation_path = 'nanos-world::A_Mannequin_Deep_Breath_Sad', slot_type = AnimationSlotType.UpperBody, loop = false },
        Dont_Know_02 = { name = 'Generic - Don\'t Know 2', animation_path = 'nanos-world::A_Mannequin_Don_t_Know_2', slot_type = AnimationSlotType.UpperBody, loop = false },
        Dont_Know = { name = 'Generic - Don\'t Know', animation_path = 'nanos-world::A_Mannequin_Dont_Know', slot_type = AnimationSlotType.UpperBody, loop = false },
        Drunk_Talk = { name = 'Generic - Drunk Talk', animation_path = 'nanos-world::A_Mannequin_Drunk_Talk', slot_type = AnimationSlotType.UpperBody, loop = false },
        Exercise_01 = { name = 'Generic - Exercise 1', animation_path = 'nanos-world::A_Mannequin_Exercise_01', slot_type = AnimationSlotType.UpperBody, loop = true },
        Exercise_02 = { name = 'Generic - Exercise 2', animation_path = 'nanos-world::A_Mannequin_Exercise_02', slot_type = AnimationSlotType.UpperBody, loop = true },
        Exercise_03 = { name = 'Generic - Exercise 3', animation_path = 'nanos-world::A_Mannequin_Exercise_03', slot_type = AnimationSlotType.UpperBody, loop = true },
        Fart = { name = 'Generic - Fart', animation_path = 'nanos-world::A_Mannequin_Fart', slot_type = AnimationSlotType.UpperBody, loop = false },
        Fixing_Something = { name = 'Generic - Fixing Something', animation_path = 'nanos-world::A_Mannequin_Fixing_Something', slot_type = AnimationSlotType.UpperBody, loop = false },
        Get_Here_01 = { name = 'Generic - Get Here 1', animation_path = 'nanos-world::A_Mannequin_Get_Here_01', slot_type = AnimationSlotType.UpperBody, loop = false },
        Get_Here_02 = { name = 'Generic - Get Here 2', animation_path = 'nanos-world::A_Mannequin_Get_Here_02', slot_type = AnimationSlotType.UpperBody, loop = false },
        Go_Away = { name = 'Generic - Go Away', animation_path = 'nanos-world::A_Mannequin_Go_Away', slot_type = AnimationSlotType.UpperBody, loop = false },
        Deal = { name = 'Generic - Deal', animation_path = 'nanos-world::A_Mannequin_Deal', slot_type = AnimationSlotType.UpperBody, loop = false },
        Head_Scratch = { name = 'Generic - Head Scratch', animation_path = 'nanos-world::A_Mannequin_Head_Scratch', slot_type = AnimationSlotType.UpperBody, loop = false },
        Hold_Baby = { name = 'Generic - Hold Baby', animation_path = 'nanos-world::A_Mannequin_Hold_Baby', slot_type = AnimationSlotType.UpperBody, loop = false },
        Idle_01 = { name = 'Generic - Idle 1', animation_path = 'nanos-world::A_Mannequin_Idle_01', slot_type = AnimationSlotType.UpperBody, loop = true },
        Idle_02 = { name = 'Generic - Idle 2', animation_path = 'nanos-world::A_Mannequin_Idle_02', slot_type = AnimationSlotType.UpperBody, loop = true },
        Idle_03 = { name = 'Generic - Idle 3', animation_path = 'nanos-world::A_Mannequin_Idle_03', slot_type = AnimationSlotType.UpperBody, loop = true },
        Idle_04 = { name = 'Generic - Idle 4', animation_path = 'nanos-world::A_Mannequin_Idle_04', slot_type = AnimationSlotType.UpperBody, loop = true },
        Idle_05 = { name = 'Generic - Idle 5', animation_path = 'nanos-world::A_Mannequin_Idle_05', slot_type = AnimationSlotType.UpperBody, loop = true },
        Idle_06 = { name = 'Generic - Idle 6', animation_path = 'nanos-world::A_Mannequin_Idle_06', slot_type = AnimationSlotType.UpperBody, loop = true },
        Itching_Body = { name = 'Generic - Itching Body', animation_path = 'nanos-world::A_Mannequin_Itching_Body', slot_type = AnimationSlotType.UpperBody, loop = false },
        Laugh = { name = 'Generic - Laugh', animation_path = 'nanos-world::A_Mannequin_Laugh', slot_type = AnimationSlotType.UpperBody, loop = false },
        Legs_Relax = { name = 'Generic - Legs Relax', animation_path = 'nanos-world::A_Mannequin_Legs_Relax', slot_type = AnimationSlotType.UpperBody, loop = false },
        Lets_Go = { name = 'Generic - Let\'s Go', animation_path = 'nanos-world::A_Mannequin_Lets_Go', slot_type = AnimationSlotType.UpperBody, loop = false },
        Look_Around = { name = 'Generic - Look Around', animation_path = 'nanos-world::A_Mannequin_Look_Around', slot_type = AnimationSlotType.UpperBody, loop = false },
        No = { name = 'Generic - No', animation_path = 'nanos-world::A_Mannequin_No', slot_type = AnimationSlotType.UpperBody, loop = false },
        Playing_Guitar = { name = 'Generic - Playing Guitar', animation_path = 'nanos-world::A_Mannequin_Playing_Guitar', slot_type = AnimationSlotType.UpperBody, loop = false },
        Salute = { name = 'Generic - Salute', animation_path = 'nanos-world::A_Mannequin_Salute', slot_type = AnimationSlotType.UpperBody, loop = false },
        Shout = { name = 'Generic - Shout', animation_path = 'nanos-world::A_Mannequin_Shout', slot_type = AnimationSlotType.UpperBody, loop = false },
        Show_Bicep = { name = 'Generic - Show Bicep', animation_path = 'nanos-world::A_Mannequin_Show_Bicep', slot_type = AnimationSlotType.UpperBody, loop = false },
        Showing_Goods_01 = { name = 'Generic - Showing Goods 01', animation_path = 'nanos-world::A_Mannequin_Showing_Goods_01', slot_type = AnimationSlotType.UpperBody, loop = false },
        Showing_Goods_02 = { name = 'Generic - Showing Goods 02', animation_path = 'nanos-world::A_Mannequin_Showing_Goods_02', slot_type = AnimationSlotType.UpperBody, loop = false },
        Sit_Bench = { name = 'Generic - Sit Bench', animation_path = 'nanos-world::A_Mannequin_Sit_Bench', slot_type = AnimationSlotType.UpperBody, loop = false },
        Smith_Working = { name = 'Generic - Smith Working', animation_path = 'nanos-world::A_Mannequin_Smith_Working', slot_type = AnimationSlotType.UpperBody, loop = false },
        Sneeze = { name = 'Generic - Sneeze', animation_path = 'nanos-world::A_Mannequin_Sneeze', slot_type = AnimationSlotType.UpperBody, loop = false },
        Stinky = { name = 'Generic - Stinky', animation_path = 'nanos-world::A_Mannequin_Stinky', slot_type = AnimationSlotType.UpperBody, loop = false },
        Take_Drink = { name = 'Generic - Take Drink', animation_path = 'nanos-world::A_Mannequin_Take_Drink', slot_type = AnimationSlotType.UpperBody, loop = false },
        Take_From_Floor = { name = 'Generic - Take From Floor', animation_path = 'nanos-world::A_Mannequin_Take_From_Floor', slot_type = AnimationSlotType.UpperBody, loop = false },
        Take_From_Table = { name = 'Generic - Take From Table', animation_path = 'nanos-world::A_Mannequin_Take_From_Table', slot_type = AnimationSlotType.UpperBody, loop = false },
        Talking_01 = { name = 'Generic - Talking 01', animation_path = 'nanos-world::A_Mannequin_Talking_01', slot_type = AnimationSlotType.UpperBody, loop = false },
        Talking_02 = { name = 'Generic - Talking 02', animation_path = 'nanos-world::A_Mannequin_Talking_02', slot_type = AnimationSlotType.UpperBody, loop = false },
        Talking_03 = { name = 'Generic - Talking 03', animation_path = 'nanos-world::A_Mannequin_Talking_03', slot_type = AnimationSlotType.UpperBody, loop = false },
        Thinking = { name = 'Generic - Thinking', animation_path = 'nanos-world::A_Mannequin_Thinking', slot_type = AnimationSlotType.UpperBody, loop = false },
        Throw_01 = { name = 'Generic - Throw 01', animation_path = 'nanos-world::A_Mannequin_Throw_01', slot_type = AnimationSlotType.UpperBody, loop = false },
        Throw_02 = { name = 'Generic - Throw 02', animation_path = 'nanos-world::A_Mannequin_Throw_02', slot_type = AnimationSlotType.UpperBody, loop = false },
        Triumph = { name = 'Generic - Triumph', animation_path = 'nanos-world::A_Mannequin_Triumph', slot_type = AnimationSlotType.UpperBody, loop = false },
        Washing_Window = { name = 'Generic - Washing Window', animation_path = 'nanos-world::A_Mannequin_Washing_Window', slot_type = AnimationSlotType.UpperBody, loop = false },
        Watching_Somewhere = { name = 'Generic - Watching Somewhere', animation_path = 'nanos-world::A_Mannequin_Watching_Somewhere', slot_type = AnimationSlotType.UpperBody, loop = false },
        Wave_01 = { name = 'Generic - Wave 01', animation_path = 'nanos-world::A_Mannequin_Wave_01', slot_type = AnimationSlotType.UpperBody, loop = false },
        Wave_02 = { name = 'Generic - Wave 02', animation_path = 'nanos-world::A_Mannequin_Wave_02', slot_type = AnimationSlotType.UpperBody, loop = false },
        Wave_03 = { name = 'Generic - Wave 03', animation_path = 'nanos-world::A_Mannequin_Wave_03', slot_type = AnimationSlotType.UpperBody, loop = false },
        -- Poses
        Box = { name = 'Poses - Box', animation_path = 'nanos-world::AM_Mannequin_Box', slot_type = AnimationSlotType.UpperBody, loop = false },
        Barrel_01 = { name = 'Poses - Barrel 1', animation_path = 'nanos-world::AM_Mannequin_Barrel_01', slot_type = AnimationSlotType.UpperBody, loop = false },
        Barrel_02 = { name = 'Poses - Barrel 2', animation_path = 'nanos-world::AM_Mannequin_Barrel_02', slot_type = AnimationSlotType.UpperBody, loop = false },
        -- Actions
        Equip = { name = 'Actions - Equip', animation_path = 'nanos-world::AM_Mannequin_Equip', slot_type = AnimationSlotType.UpperBody, loop = false },
        Unequip = { name = 'Actions - Unequip', animation_path = 'nanos-world::AM_Mannequin_Unequip', slot_type = AnimationSlotType.UpperBody, loop = false },
        DoorOpen_01 = { name = 'Actions - Door Open 01', animation_path = 'nanos-world::AM_Mannequin_DoorOpen_01', slot_type = AnimationSlotType.FullBody, loop = false },
        DoorOpen_02 = { name = 'Actions - Door Open 02', animation_path = 'nanos-world::AM_Mannequin_DoorOpen_02', slot_type = AnimationSlotType.FullBody, loop = false },
        DoorOpen_03 = { name = 'Actions - Door Open 03', animation_path = 'nanos-world::AM_Mannequin_DoorOpen_03', slot_type = AnimationSlotType.FullBody, loop = false },
        DoorOpen_04 = { name = 'Actions - Door Open 04', animation_path = 'nanos-world::AM_Mannequin_DoorOpen_04', slot_type = AnimationSlotType.FullBody, loop = false },
        -- Melee
        Stab_Attack = { name = 'Melee - Stab_Attack', animation_path = 'nanos-world::AM_Mannequin_Melee_Stab_Attack', slot_type = AnimationSlotType.FullBody, loop = false },
        Slash_Attack = { name = 'Melee - Slash Attack', animation_path = 'nanos-world::AM_Mannequin_Melee_Slash_Attack', slot_type = AnimationSlotType.FullBody, loop = false },
        Bayonet_Stab_Attack = { name = 'Melee - Bayonet Stab', animation_path = 'nanos-world::AM_Mannequin_Melee_Bayonet_Stab_Attack', slot_type = AnimationSlotType.FullBody, loop = false },
        Torch_Attack = { name = 'Melee - Torch Attack', animation_path = 'nanos-world::AM_Mannequin_Torch_Attack', slot_type = AnimationSlotType.FullBody, loop = false },
        -- Locomotion
        Standing_IdleWalkRun = { name = 'Locomotion - Standing IdleWalkRun', animation_path = 'nanos-world::BS_Mannequin_Standing_IdleWalkRun', slot_type = AnimationSlotType.FullBody, loop = false },
        Crouching_IdleWalkRun = { name = 'Locomotion - Crouching IdleWalkRun', animation_path = 'nanos-world::BS_Mannequin_Crouching_IdleWalkRun', slot_type = AnimationSlotType.FullBody, loop = false },
        Proning_IdleWalk = { name = 'Locomotion - Proning IdleWalk', animation_path = 'nanos-world::BS_Mannequin_Proning_IdleWalk', slot_type = AnimationSlotType.FullBody, loop = false },
        StandingToCrouching = { name = 'Locomotion - Transition Standing to Crouching', animation_path = 'nanos-world::A_Mannequin_StandingToCrouching', slot_type = AnimationSlotType.FullBody, loop = false },
        CrouchingToStanding = { name = 'Locomotion - Transition Crouching to Standing', animation_path = 'nanos-world::A_Mannequin_CrouchingToStanding', slot_type = AnimationSlotType.FullBody, loop = false },
        ProningToCrouching = { name = 'Locomotion - Transition Proning to Crouching', animation_path = 'nanos-world::A_Mannequin_ProningToCrouching', slot_type = AnimationSlotType.FullBody, loop = false },
        CrouchingToProne = { name = 'Locomotion - Transition Crouching to Prone', animation_path = 'nanos-world::A_Mannequin_CrouchingToProne', slot_type = AnimationSlotType.FullBody, loop = false },
    }
}
